---
version: 2.1
orbs:
  aws: willbengtson/aws-assume-role@dev:alpha


workflows:
    version: 2
    test-workflow:
        jobs:
          - test:
              filters:
                branches:
                  only:
                    - master


jobs:

  
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          command: echo "Hello"

      - aws/assume_role:
          account_id: 
          role_name: